package com.fota.trade.common;

import lombok.Getter;

/**
 * @author Gavin Shen
 * @Date 2018/7/7
 */
public enum ResultCodeEnum {
    SUCCESS(0,"SUCCESS"),
    SYSTEM_ERROR(100001, "SYSTEM_ERROR"),
    // 参数异常
    ILLEGAL_PARAM(11001, "ILLEGAL_PARAM"),
    DATABASE_EXCEPTION(11002, "DATABASE_EXCEPTION"),
    BEAN_COPY_EXCEPTION(11003, "BEAN_COPY_EXCEPTION"),
    SERVICE_EXCEPTION(11004, "SERVICE_EXCEPTION"),
    SERVICE_FAILED(11005, "SERVICE_FAILED"),
    ASSET_SERVICE_FAILED(11006, "SERVICE_FAILED"),
    /**
     * 业务异常
     */
    NO_CANCELLABLE_ORDERS(120001, "NO_CANCELLABLE_ORDERS"),
    CLOSE_POSITION_FAILED(120002, "CLOSE_POSITION_FAILED"),
    CONTRACT_IS_DELIVERYING(120003, "CONTRACT_IS_DELIVERYING"),
    CONTRACT_HAS_DELIVERIED(120004, "CONTRACT_HAS_DELIVERIED"),
    CONTRACT_IS_ROLLING_BACK(120005, "CONTRACT_IS_ROLLING_BACK"),
    PRICE_OUT_OF_RANGE(120006, "PRICE_OUT_OF_RANGE"),
    MODIFY_LEVER_FAILED(120007, "MODIFY_LEVER_FAILED"),
    CANCEL_ORDER_FAILED(120008, "CANCEL_ORDER_FAILED"),
    UNFENISHED_ORDER(120009, "UNFENISHED_ORDER"),
    PARTLY_COMPLETED(120010, "PARTLY_COMPLETED"),
    CONTRACT_ROLLBACKING(120011,"contract is rollbacking"),
    ORDER_FAILED(120012, "ORDER_FAILED"),
    USDT_CAPITAL_ACCOUNT_AMOUNT_NOT_ENOUGH(120013, "USDT_CAPITAL_ACCOUNT_AMOUNT_NOT_ENOUGH"),
    COIN_CAPITAL_ACCOUNT_AMOUNT_NOT_ENOUGH(120014, "COIN_CAPITAL_ACCOUNT_AMOUNT_NOT_ENOUGH"),
    CONTRACT_ACCOUNT_AMOUNT_NOT_ENOUGH(120015, "CONTRACT_ACCOUNT_AMOUNT_NOT_ENOUGH"),
    CANCEL_ALL_ORDER_FAILED(120016, "CANCEL_ALL_ORDER_FAILED"),
    UPDATE_CONTRACT_ORDER_FAILED(120016, "UPDATE_CONTRACT_ORDER_FAILED"),

    ;
    @Getter
    private int code;
    @Getter
    private String message;

    ResultCodeEnum(int code, String message) {
        this.code = code;
        this.message = message;
    }

}
