package com.fota.client.common;

import lombok.Getter;

/**
 * @author Gavin Shen
 * @Date 2018/7/7
 */
public enum  ResultCodeEnum {
    SUCCESS(0,"SUCCESS"),
    // 参数异常
    ILLEGAL_PARAM(11001, "ILLEGAL_PARAM"),
    DATABASE_EXCEPTION(11002, "DATABASE_EXCEPTION"),
    BEAN_COPY_EXCEPTION(11003, "BEAN_COPY_EXCEPTION"),
    SERVICE_EXCEPTION(11004, "SERVICE_EXCEPTION"),
    SERVICE_FAILED(11005, "SERVICE_FAILED"),

    //业务异常
    CREATE_USDKORDER_FAILED(12001, "CREATE_USDKORDER_FAILED"),
    UPDATE_USDKORDER_FAILED(12002, "UPDATE_USDKORDER_FAILED"),
    ORDER_IS_CANCLED(12003, "ORDER_HAS_BEEN_CANCLED"),
    ORDER_STATUS_ILLEGAL(12004, "ORDER_STATUS_ILLEGAL"),
    NO_CANCELLABLE_ORDERS(12005, "THERE_ARE_NO_CANCELLABLE_ORDERS"),
    ASK_AND_BID_ILLEGAL(12006, "ASK_AND_BID_ILLEGAL"),
    ASK_ILLEGAL(12007, "ASK_ILLEGAL"),
    BID_ILLEGAL(12008, "BID_ILLEGAL"),
    ORDER_UNFILLEDAMOUNT_NOT_ENOUGHT(12009, "ORDER_UNFILLEDAMOUNT_NOT_ENOUGHT"),
    UPDATE_USDK_CAPITAL_LOCKEDAMOUNT_FAILED(12010, "UPDATE_USDK_CAPITAL_LOCKEDAMOUNT_FAILED"),
    USDK_CAPITAL_AMOUNT_NOT_ENOUGH(12011, "USDK_CAPITAL_AMOUNT_NOT_ENOUGH"),
    UPDATE_COIN_CAPITAL_LOCKEDAMOUNT_FAILED(12012, "UPDATE_COIN_CAPITAL_LOCKEDAMOUNT_FAILED"),
    COIN_CAPITAL_AMOUNT_NOT_ENOUGH(12013, "COIN_CAPITAL_AMOUNT_NOT_ENOUGH"),



    ;
    @Getter
    private int code;
    @Getter
    private String message;

    ResultCodeEnum(int code, String message) {
        this.code = code;
        this.message = message;
    }

}
